### ISSUE TITLE
Support for multiple URLs

### ISSUE THREAD

**Issue by michael1026** [Sh1Yo/x8#10] opened 2021-08-12 19:35 UTC
Hi

This project looks great. I was interested in using it, but it doesn't seem like it supports scanning multiple URLs in one go. I understand you can probably just create a bash loop, but then you end up with tons of output files instead of one, without a simple way of combining them (like JSON files).

**Comment by Sh1Yo** [comment] 2021-08-13 05:00
Hi. You can combine all json files with `jq`:
![image](https://user-images.githubusercontent.com/54232788/129306756-93fc48fb-0c3a-422d-85d6-eefe71123e49.png)

If it isn't something you need, I will consider creating a wrapper or something.

**Comment by michael1026** [comment] 2021-08-13 06:26
Interesting. I didn't know `jq` could do that. I'll try that out. Thanks.

**Comment by Sh1Yo** [comment] 2021-08-14 06:56
Well I am closing this then..

**Closed by Sh1Yo** 2021-08-14 06:56 UTC

**Comment by 0xgaurang** [comment] 2021-08-15 12:28
@Sh1Yo I too have this question. The problem is getting output when multiple URL's are supplied to x8.

Here's the command I'm trying to run:
```
cat urls.txt | xargs -n 1 -I{} x8 -w params -u {} -O url -o output.txt
```
Is there a way to get output of multiple URLs that were supplied to x8? The problem when running above command is that the results are overwritten in output.txt and finally you just get a single result of the last URL that ran.

**Comment by Sh1Yo** [comment] 2021-08-15 12:43
@0xgaurang you can try something like
```bash
a=0;for url in `cat urls.txt`; do a=$(($a+1)); x8 -w params -u $url -O url -o ${a}output.txt; done
```
If you for some reason need xargs, and you don't need the output to the console, you can try
```bash
cat urls.txt | xargs -n 1 -I{} x8 -v 0 -w params -u {} -O url >> output.txt
```

**Comment by 0xgaurang** [comment] 2021-08-15 14:18
Awesome. Thanks!
